### ISSUE TITLE
Overview docs on how to get tracks into free rider

### ISSUE THREAD

**Issue by kovasap** [Calculamatrise/frhd#2]
I'm working on a project to generate free rider tracks programmatically and have them be playable in free rider.  Ideally my final product would be a "Export to free rider" button on a website that, when clicked, generates a free rider track using my code, then opens it directly in free rider.

It seems like this project will be able to help me do at least the track generation part of this.  I'm still a bit confused on how I would take my final track and open it in free rider (ideally with one click).  Are there any docs about this?

**Comment by Calculamatrise** [comment]
Not exactly. But if I understood correctly, you would want to upload the track, then fetch the user account which you used to upload the track, access its tracks and sort them by the upload date, then you could take the track ID and attach it to the end of this URI: https://frhd.co/t/TRACK_ID_HERE

**Comment by kovasap** [comment]
Yes that's correct. I didn't really think about the sign-in aspect before.  Given that, perhaps it would be more ergonomic to pre-generate the tracks in batch, uploading to a single user, then simply link to the tracks directly from my "export to free rider" button.  I'd like to avoid having my users need to make a free rider account to use the button.

**Comment by Calculamatrise** [comment]
You could create an account, login using the API, then post the tracks to that account upon generating them.
